Added support for % and ^ (percent and exponentiation) to expression …
project-jedi/jcl pull request #108
Opened 2021-09-23 12:45 UTC by bennybechdk

…evaluator.

Has been in use in a commercial product since 2016

exsamples:
 123*10%   gives 12.3
2^8 give 256

2021-09-23 13:09 UTC, obones requested changes

2021-09-23 13:09 UTC, obones commented on jcl/source/common/JclExprEval.pas
> +  Math,
This one should be in the "HAS_UNITSCOPE" section, with its prefixed counterpart in IF part

2021-09-23 13:09 UTC, obones commented on jcl/source/common/JclExprEval.pas
> +          Lexer.NextTok;
Why is the NextTok call required here? It's not used in any of the other elements of the case which makes me wonder...

2021-09-23 13:09 UTC, obones commented on jcl/source/common/JclExprEval.pas
> +          Lexer.NextTok;
Same remark as above

2021-09-24 09:00 UTC, bennybechdk commented
Thanks for the comments

2021-09-24 09:05 UTC, obones approved these changes

2021-09-24 09:05 UTC, merged