Bios date location changed in W10
project-jedi/jcl pull request #122
Opened 2022-11-30 12:19 UTC by fschenckel

Bios date location in registry seems to have changed at least since W10

2022-11-30 14:29 UTC, ronaldhoek commented
Sorry, you'll need to add some backward compatibility: detect if OS is Win10 (or higher?) and then use the corresponding registry keys based on the detection (old vs new)

2022-11-30 14:41 UTC, fschenckel commented
Hi,

The problem is I couldn't get any information regarding both keys... The only thing I'm sure is that the new key I propose to use is already existing in Win7.
The official version is failing on W10 and higher.

I could eventually check if OS > Win7 ?

Regards

Frédéric SCHENCKEL

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
cab technologies
za Nord du val de Moder
67350 Niedermodern
Tél: + 33 3 88 72 25 01 / Fax: +33 3 88 72 25 02
Notre site en Français: www.cab-technologies.fr<http://www.cab-technologies.fr/>
Adresse support: ***@***.******@***.***>
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

De : Ronald Hoek ***@***.***>
Envoyé : mercredi 30 novembre 2022 15:29
À : project-jedi/jcl ***@***.***>
Cc : Frédéric SCHENCKEL ***@***.***>; Author ***@***.***>
Objet : Re: [project-jedi/jcl] Bios date location changed in W10 (PR #122)


Sorry, you'll need to add some backward compatibility: detect if OS is Win10 (or higher?) and then use the corresponding registry keys based on the detection (old vs new)

-
Reply to this email directly, view it on GitHub<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fproject-jedi%2Fjcl%2Fpull%2F122%23issuecomment-1332233823&data=05%7C01%7Cf.schenckel%40cab-technologies.fr%7C0b7b8088cf534c00be5108dad2df42a4%7C68d3308db7f840dabfac9558bb2d0491%7C0%7C0%7C638054153590274450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1UhJUw0p0nfpBptXzSQk%2FwJqvc93a86%2Fz87NwWMVqlI%3D&reserved=0>, or unsubscribe<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACCVLQEYHWVWNDE5ANDJ6MTWK5QDXANCNFSM6AAAAAASPSELUE&data=05%7C01%7Cf.schenckel%40cab-technologies.fr%7C0b7b8088cf534c00be5108dad2df42a4%7C68d3308db7f840dabfac9558bb2d0491%7C0%7C0%7C638054153590274450%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=usVKrme68LHa1YLnT5cCBZZ8H8kij09sox9QrKj27T4%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-11-30 14:52 UTC, ronaldhoek commented
Ok, don't have any knowledge about the keys either.

Another idea would be to first use the new key and when no value is found, use the old key?

2022-11-30 15:13 UTC, fschenckel commented
OK, yes I can do it this way:
1) Check for the 'new' key (W10 and newer => Most probability today)
2) if not existing use the key as it is done today, so we will have the same behavior regarding exception and so on...

2023-07-31 11:49 UTC, ronaldhoek commented
@obones can you merge this - I can see the date a the new location (in my Win10 setup) and no longer at the old location - so regarding backward compatibility it looks fine.

2023-08-01 20:14 UTC, obones commented on jcl/source/common/JclSysInfo.pas
> +  WinNT_REG_KEY_OLD  = 'SystemBiosDate';
I dislike the "new"/"old" naming as it doesn't convey any meaning as to when the change happened. And what if it changes again? Will it then be "NEW_NEW" or "NEW_2"?
I'd rather keep `WinNT_REG_PATH` and `WinNT_REG_KEY` introduce `WIN10_REG_PATH` and `WIN10_REG_KEY` both declared together right after the `const` line

2023-08-01 20:15 UTC, obones commented on jcl/source/common/JclSysInfo.pas
> +  if IsWinNT then begin
The coding style guide mandates that `begin` be placed on its own line.
Also, if a branch of the `if`/`else` statement requires a `begin`/`end` block, then the other part must have it also.

2023-08-01 20:16 UTC, obones commented on jcl/source/common/JclSysInfo.pas
> +    The new location seems to exist since a while, but older location disappeared on newer OS}
No need for the initials and the date. Also, two lines comments like this one should not use the curly braces style but rather the two slashes style, repeated on both lines

2023-08-01 20:17 UTC, obones commented on jcl/source/common/JclSysInfo.pas
> +      {New location}
Please remove this line

2023-08-01 20:17 UTC, obones commented on jcl/source/common/JclSysInfo.pas
> +      {Old location}
Please remove this line

2023-08-30 13:43 UTC, obones requested changes

2023-08-30 13:43 UTC, obones commented on jcl/source/common/JclSysInfo.pas
>      RegStr := RegReadString(HKEY_LOCAL_MACHINE, Win9x_REG_PATH, Win9x_REG_KEY);
The coding style mandates that if a branch of the if/else statement requires a begin/end block, then the other part must have it also.
So please add a begin/end statement around this one

2023-08-30 13:54 UTC, merged