Update pronouns to gender neutral variants
project-jedi/jcl pull request #149
Opened 2024-10-29 17:16 UTC by Arctic-Circuits

Change exception messages and a comment from male pronouns to gender neutral pronouns.

2025-01-03 08:16 UTC, obones commented on jcl/source/common/JclSysUtils.pas
> +  // The user must release shared memory blocks himself. We don't clean up their
I'm not a native speaker but it feels weird having "himself" followed by "their".

2025-01-10 17:14 UTC, Arctic-Circuits commented
Oh, I missed that. Thanks. I'll update it.

On Fri, Jan 3, 2025 at 3:16 AM obones ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In jcl/source/common/JclSysUtils.pas
> <https://github.com/project-jedi/jcl/pull/149#discussion_r1901555664>:
>
> > @@ -4528,7 +4528,7 @@ finalization
>    {$ENDIF UNITVERSIONING}
>    {$IFDEF MSWINDOWS}
>    {$IFDEF THREADSAFE}
> -  // The user must release shared memory blocks himself. We don't clean up his
> +  // The user must release shared memory blocks himself. We don't clean up their
>
> I'm not a native speaker but it feels weird having "himself" followed by
> "their".
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/project-jedi/jcl/pull/149#pullrequestreview-2528694289>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGEUVVEM7GENQ4SCTRXQJ7D2IZBO5AVCNFSM6AAAAABQ2LKMGOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMRYGY4TIMRYHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-31 09:57 UTC, obones requested changes

2025-01-31 09:57 UTC, obones commented on jcl/source/common/JclSysUtils.pas
> +  FMultiplier := '×';
This should not have been changed, the encoding of JCL files must never be UTF-8 as it is not understood by early versions of Delphi/BCB

2026-05-07 20:00 UTC, merged